SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
SELECT * FROM PIZZA;
SELECT * FROM TOPPINGS;
SELECT * FROM TOPPINGS_ON_PIZZA;
SELECT * FROM BASE_PRICES;
SELECT * FROM DISCOUNTS;
SELECT * FROM DISCOUNT_TO_ORDER;
SELECT * FROM DINE_IN;
SELECT * FROM DELIVERY;
SELECT * FROM PICKUP;
SELECT * FROM STATUS;


